# Generated by Django 3.2.4 on 2021-06-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(default='', max_length=100)),
                ('nome', models.CharField(default='', max_length=100, null=True)),
                ('cargo', models.CharField(max_length=500)),
                ('telefone', models.CharField(default='', max_length=15, null=True)),
                ('email', models.CharField(default='', max_length=200, null=True)),
                ('link', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
    ]
